- name: Give permissions to frapper user 
  hosts: all
  become: yes
  become_user: root
  roles: 
    - add_permissions
  tags: 
    - add_permissions

- name: Run migrate bench commands 
  hosts: all
  gather_facts: yes
  become: yes
  become_user: frappe
  roles:
    - migrate 
  tags: 
    - migrate 

- name: Remove permissions from frapper user 
  hosts: all
  become: yes
  gather_facts: no
  become_user: root 
  roles: 
    - remove_permissions
  tags: 
    - remove_permissions 
