- name: Give permissions to frapper user
  hosts: all
  become: yes
  become_user: root
  roles:
    - frappe/add_permissions
  tags:
    - add_permissions

- name: Run get-app on bench directory
  hosts: all
  gather_facts: yes
  become: yes
  become_user: frappe
  roles:
    - frappe/get-app
  tags:
    - get-app
  ignore_errors: yes

- name: Run install-app for a site
  hosts: all
  gather_facts: yes
  become: yes
  become_user: frappe
  roles:
    - frappe/install_app
  tags:
    - install_app
  ignore_errors: yes

- name: Git pull the new changes
  hosts: all
  gather_facts: yes
  become: yes
  become_user: frappe
  roles:
    - frappe/git_pull
  tags:
    - git_pull
  ignore_errors: yes


- name: Run migrate bench command for the site
  hosts: all
  gather_facts: yes
  become: yes
  become_user: frappe
  roles:
    - frappe/migrate
  tags:
    - migrate
  ignore_errors: yes

- name: Remove permissions from frapper user
  hosts: all
  become: yes
  gather_facts: no
  become_user: root
  roles:
    - frappe/remove_permissions
  tags:
    - remove_permissions

- name: TOP the Server
  hosts: all
  become: yes
  gather_facts: no
  become_user: root
  roles:
    - frappe/top
  tags:
    - top

- name: Nopassword for Frappe
  hosts: all
  become: yes
  become_user: root
  roles:
    - frappe/nopassword_frappe
  tags:
    - nopassword_frappe
