- name: Give permissions to frapper user
  hosts: all
  become: yes
  become_user: root
  roles:
    - add_permissions
  tags:
    - add_permissions

- name: Git pull the new changes
  hosts: all
  gather_facts: yes
  become: yes
  become_user: frappe
  roles:
    - git_pull
  tags:
    - git_pull
  ignore_errors: yes


- name: Clear cache and website-cache
  hosts: all
  gather_facts: yes
  become: yes
  become_user: frappe
  roles:
    - clear_cache
  tags:
    - clear_cache
  ignore_errors: yes

- name: Run migrate bench command for the site
  hosts: all
  gather_facts: yes
  become: yes
  become_user: frappe
  roles:
    - migrate
  tags:
    - migrate
  ignore_errors: yes

- name: Bench Restart
  hosts: all
  gather_facts: yes
  become: yes
  become_user: frappe
  roles:
    - restart
  tags:
    - restart
  ignore_errors: yes


- name: Remove permissions from frapper user
  hosts: all
  become: yes
  gather_facts: no
  become_user: root
  roles:
    - remove_permissions
  tags:
    - remove_permissions

